name: CICD pipeline of article

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4  
        with:
          node-version: "20"

      - name: check syntax
        run: find . -name "*.js" -exec node --check {} +

  trivy_scan:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with: 
          scan-type: "fs"
          format: "table"
          scan-ref: "."
          severity: "HIGH,CRITICAL"
          ignore-unfixed: true
          exit-code: 1

  gitleaks_scans:
    runs-on: ubuntu-latest
    needs: trivy_scan

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: gitleaks setup
        uses: gitleaks/gitleaks-action@v2

      - name: gitleaks scan
        run: gitleaks detect --source . --exit-code 1
